import json
import pandas as pd

from concurrent.futures import ThreadPoolExecutor
from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field
from typing import Literal

from evaluation_utils import calc_total_price, llm_structured_retry, map_progress


load_dotenv()
llm_client = OpenAI()

agent_answers = pd.read_csv("./data/agent-answers.csv").to_dict(orient="records")

class AgentEvaluation(BaseModel):
    answer_reasoning: str = Field(
        description="Reasoning about whether the final answer is correct"
    )
    answer_score: Literal["good", "bad"] = Field(
        description="good if the final answer is correct otherwise bad"
    )
    trajectory_reasoning: str = Field(
        description="Reasoning about whether the tool calls are useful"
    )
    trajectory_score: Literal["good", "bad"] = Field(
        description="good if the tool calls were reasonable for the question, otherwise bad"
    )

judge_instructions = """
You are an expert evaluator. You will be given:
1. A question from a student
2. The original answer from the FAQ (ground truth)
3. An answer generated by an AI agent
4. The tool calls made by the agent

Evaluate two things:

Answer quality:
- Does the agent answer match the original answer?
- It does not need to be word-for-word identical.
- It should contain the same key information.

Trajectory quality:
- Were the search queries relevant to the question?
- Did the queries include important keywords from the question?
- Did the agent avoid duplicate or unnecessary tool calls?
- If it made multiple searches, did the later searches refine the query?
- Was the number of search calls reasonable? Usually 1 is enough, 2-3
  can be okay, and more than 3 needs a clear reason.
- Did the tool calls support the final answer?

Mark answer_score as 'good' if the final answer is correct.
Mark trajectory_score as 'good' if the tool calls were reasonable.
""".strip()

agent_judge_prompt = """
Question:
{question}

Original Answer (ground truth):
{answer_orig}

Agent Answer:
{answer_agent}

Tool Calls:
{tool_calls}
""".strip()

def evaluate_agent_answer(rec, model="gpt-5.4-mini"):
    tool_calls = rec["tool_calls"]

    if isinstance(tool_calls, str):
        tool_calls = json.loads(tool_calls)

    prompt = agent_judge_prompt.format(
        question=rec["question"],
        answer_orig=rec["answer_orig"],
        answer_agent=rec["answer_agent"],
        tool_calls=tool_calls
    )

    result, usage = llm_structured_retry(
        client = llm_client,
        instructions=judge_instructions,
        user_prompt=prompt,
        output_type=AgentEvaluation,
        model=model
    )

    result = {
        "question": rec["question"],
        "document": rec["document"],
        "answer_score": result.answer_score,
        "answer_reasoning": result.answer_reasoning,
        "trajectory_score": result.trajectory_score,
        "trajectory_reasoning": result.trajectory_reasoning,
    }

    return result, usage

with ThreadPoolExecutor(max_workers=4) as pool:
    results = map_progress(pool, agent_answers, evaluate_agent_answer)

evaluations = []
usages = []

for evaluation, usage in results:
    evaluations.append(evaluation)
    usages.append(usage)

print(calc_total_price(usages))

df_agent_evals = pd.DataFrame(evaluations)
df_agent_evals.to_csv("./data/agent_evaluation_scores.csv", index=False)

print(df_agent_evals["answer_score"].value_counts())
print(df_agent_evals["trajectory_score"].value_counts())
