import pandas as pd

from concurrent.futures import ThreadPoolExecutor
from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field
from typing import Literal

from evaluation_utils import (
    calc_price,
    calc_total_price,
    llm_structured_retry,
    map_progress,
)

load_dotenv()
openai_client = OpenAI()

rag_answers = pd.read_csv("./data/rag_answers.csv").to_dict(orient="records")


class AnswerEvaluation(BaseModel):
    reasoning: str = Field(description="Helps us know about why answer is good or bad")
    score: Literal["good", "bad"] = Field(
        description="Good if answer is complete and correct, otherwise bad"
    )


rag_evaluation_instructions = """
You are an expert evaluator. You will be given:
1. A question from a student
2. The original answer for that question
3. An answer generated by an LLM, like you.

Your task is to decide if the LLM answer is semantically equivalent to
the original answer.

Rules:
- The LLM answer does NOT need to be word-for-word identical
- It should convey the same key information
- Extra detail is fine as long as the core answer is correct
- Mark 'bad' only if the AI answer is wrong or misses the key point

Be fair and focus on correctness, not style.
""".strip()

llm_judge_prompt = """
Question:
{question}

Original Answer (ground truth):
{original_answer}

AI Answer:
{llm_answer}
""".strip()


def evaluate_rag(record):

    result, usage = llm_structured_retry(
        client=openai_client,
        instructions=rag_evaluation_instructions,
        user_prompt=llm_judge_prompt.format(
            question=record["question"],
            original_answer=record["original_answer"],
            llm_answer=record["llm_answer"],
        ),
        output_type=AnswerEvaluation,
    )

    result = {
        "document_id": record["document"],
        "evaluation_score": result.score,
        "reasoning": result.reasoning 
    }

    return result, usage

def judge_all_records(records):

    with ThreadPoolExecutor(max_workers=4) as pool:
        results = map_progress(pool, records, evaluate_rag)

    return results

evaluations = []
usages = []

for evaluation, usage in judge_all_records(rag_answers):
    evaluations.append(evaluation)
    usages.append(usage)

print(f"Usage: {calc_total_price(usages)}")

df_eval = pd.DataFrame(evaluations)

good_count = (df_eval["evaluation_score"] == "good").sum()
total_count = len(df_eval)
print(f"Good: {good_count}/{total_count} = {good_count/total_count:.2%}")

print(df_eval[df_eval["evaluation_score"] == "bad"].head())

df_eval.to_csv("./data/llm_evaluation_scores.csv", index=False)



